using System;
using KiwiCommonDatabase;
using SimpleSQL;

[System.Serializable]
public class LevelReward : BaseDbModel, IResourceUpdate
{
	// id is generated by the database and set on the object automagically
	[PrimaryKey]
	public int id { get; set;}

	public int levelId{get; set;}

	[Ignore]
	private Level _level;
	[Ignore]
	public Level level{
		get{
			if(_level == null){
				_level = DatabaseManager.GetLevel(levelId);
			}
			return _level;
		}
		set{
			levelId = value.id;
		}
	}

	public string resourceId {get; set;}
	[Ignore]
	private DbResource _resource;
	[Ignore]
	public DbResource resource {
		get {
			if (_resource == null)
				_resource = DatabaseManager.GetDbResource(resourceId);
			return _resource;
		}
		set {
			resourceId = value.id;
		}
	}

	public int quantity { get; set;}

	public static string LEVEL_COLUMN = "levelId";


	public LevelReward() {
		// needed by ormlite
	}
	
	LevelReward(int id, Level level, DbResource res, int quantity) {
		this.id = id ;
		this.level = level ;
		this.resource = res ;
		this.quantity = quantity ;
	}
	
	public void setLevel(Level level){
		this.level = level;
	}
	

	public string getMD5HashString() {
		return ""+ id+level.id+resource+quantity;
	}

	#region IResourceUpdate implementation
	
	public IGameResource GetResource ()
	{
		return resource;
	}
	
	public int GetQuantity ()
	{
		return quantity;
	}
	
	#endregion




}

